version: '3.2'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis:7
    # restart: always
    ports:
      - '6379:6379'
